### ISSUE TITLE
Use `shutil.copy` instead of `defaults export`, x30 speed boost

### ISSUE THREAD

**Issue by Bobronium** [Tatsh/macprefs#3]
Instead of launching subprocess for each domain to export `.plist`, you can just use `shutil.copy(str(plist_path), str(plist_out))`.

.plist path for `-globalDomain` is `~/Library/Preferences/.GlobalPreferences.plist`

**Comment by Tatsh** [comment]
Can you make a PR?

**Comment by Bobronium** [comment]
I don't think I want to, sorry.

If anyone up to this, I can help by answering some concrete questions maybe.

**Comment by movrsi** [comment]
ill take this issue; seems simple enough.

**Comment by movrsi** [comment]
> I don't think I want to, sorry.
> 
> If anyone up to this, I can help by answering some concrete questions maybe.

Please go into a bit of detail of this issue for me if you could please, ill take this issue and do the work.

**Comment by movrsi** [comment]
> @movrsi, here's the function that contain `defaults export ...` cmd invocation, so you'd have to rewrite it:
> 
> https://github.com/Tatsh/macprefs/blob/5b66738da6d5ecb542a933d55148d47585ada923/macprefs/command.py#L43
> 
> It should be refactored to synchronous function, considering it won't require invoking subprocess anymore.

seems simple enough; ill have a pr in a few days currently working on another project. should be-able to do so in a couple of lines.
